
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "controle-node"

   config.vm.network "private_network", ip: "192.168.56.18"

   config.vm.synced_folder ".", "/vagrant", type: "nfs"

   config.vm.provision "shell", path: "provision.sh"

end


