Vagrant.configure("2") do |config|
    
    config.vm.box = "centos/7"
    
    config.vm.hostname = "app01"

    config.vm.network "private_network", ip: "192.168.56.19"
    
    config.vm.synced_folder ".", "/vagrant", type: "nfs"

    config.vm.network "forwarded_port", guest: 8000, host: 8000
    
    config.vm.provision "shell", path: "provision.sh"
  
  end
  
  
  