Vagrant.configure("2") do |config|
    
    config.vm.box = "centos/7"
    
    config.vm.hostname = "app01"

    config.vm.network "public_network", use_dhcp_assigned_default_route: true#, bridge: "wlp2s0"
    
    config.vm.synced_folder ".", "/vagrant", type: "nfs"

    config.vm.network "forwarded_port", guest: 8000, host: 8000
    
    config.vm.provision "shell", path: "provision.sh"
  
  end
  
  
  